pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'echo $PWD'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                sh 'echo $PWD'
            }
            post {
                always {
                    sh 'echo $PWD'
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo $PWD'
                sh './jenkins/scripts/deliver.sh UTF-8'
            }
        }
    }
}
